House type
schiedel-sweden/web-app pull request #2
Opened 2018-01-12 17:59 UTC by JonathanPartain

2018-01-13 16:45 UTC, jeremydanner requested changes

2018-01-13 16:45 UTC, jeremydanner commented on src/env.js
> +
env filen ska var med i `.gitignore` Jag kommer även stänga ner API't snart så dra ner apit på datorn och kör det där istället!

2018-01-15 17:12 UTC, JonathanPartain commented on src/env.js
> +
Borde vara löst i följande commits!

2018-01-21 21:17 UTC, jeremydanner approved these changes

2018-01-22 12:31 UTC, merged