Bootstrap
schiedel-sweden/web-app pull request #9
Opened 2018-01-26 18:29 UTC by JonathanPartain

2018-01-26 18:30 UTC, JonathanPartain commented
@asmatkhan Kolla gärna så att detta inte stör någon styling som du redan gjort i någon annan pull request!

2018-01-29 07:22 UTC, jeremydanner requested changes

2018-01-29 07:22 UTC, jeremydanner commented on src/App.js
> +                                rabatt: 0,
Svenska?

2018-01-29 10:40 UTC, JonathanPartain commented on src/App.js
> +                                rabatt: 0,
Norska, precis som antal, pris och sum

2018-01-30 17:22 UTC, merged